version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=divisas.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: ["python", "divisas.py"]
